# Generated by Django 2.2.5 on 2020-01-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mikrotik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('login', models.CharField(default='admin', max_length=264)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('ip', models.CharField(default='192.168.0.88', max_length=15)),
                ('timestamp_lastupdated', models.DateTimeField(auto_now=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
