# Generated by Django 2.2.5 on 2020-01-22 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_RB_app', '0002_auto_20200122_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='mikrotik',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='login_RB_app.Categoria'),
        ),
    ]
