# Generated by Django 2.2.5 on 2020-01-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_RB_app', '0003_auto_20200122_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotik',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_RB_app.Categoria'),
        ),
    ]
