# Generated by Django 3.0.2 on 2020-02-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_RB_app', '0004_auto_20200122_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotik',
            name='ip',
            field=models.GenericIPAddressField(default='192.168.0.88', protocol='IPv4'),
        ),
    ]
